In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('data/zomato_restaurants_in_India.csv')

In [3]:
df.head()

,res_id,name,establishment,url,address,city,city_id,locality,latitude,longitude,...,price_range,currency,highlights,aggregate_rating,rating_text,votes,photo_count,opentable_support,delivery,takeaway
0,3400299,Bikanervala,['Quick Bites'],https://www.zomato.com/agra/bikanervala-khanda...,"Kalyani Point, Near Tulsi Cinema, Bypass Road,...",Agra,34,Khandari,27.211450,78.002381,...,2,Rs.,"['Lunch', 'Takeaway Available', 'Credit Card',...",4.4,Very Good,814,154,0.0,-1,-1
1,3400005,Mama Chicken Mama Franky House,['Quick Bites'],https://www.zomato.com/agra/mama-chicken-mama-...,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra,34,Agra Cantt,27.160569,78.011583,...,2,Rs.,"['Delivery', 'No Alcohol Available', 'Dinner',...",4.4,Very Good,1203,161,0.0,-1,-1
2,3401013,Bhagat Halwai,['Quick Bites'],https://www.zomato.com/agra/bhagat-halwai-2-sh...,"62/1, Near Easy Day, West Shivaji Nagar, Goalp...",Agra,34,Shahganj,27.182938,77.979684,...,1,Rs.,"['No Alcohol Available', 'Dinner', 'Takeaway A...",4.2,Very Good,801,107,0.0,1,-1
3,3400290,Bhagat Halwai,['Quick Bites'],https://www.zomato.com/agra/bhagat-halwai-civi...,"Near Anjana Cinema, Nehru Nagar, Civil Lines, ...",Agra,34,Civil Lines,27.205668,78.004799,...,1,Rs.,"['Takeaway Available', 'Credit Card', 'Lunch',...",4.3,Very Good,693,157,0.0,1,-1
4,3401744,The Salt Cafe Kitchen & Bar,['Casual Dining'],https://www.zomato.com/agra/the-salt-cafe-kitc...,"1C,3rd Floor, Fatehabad Road, Tajganj, Agra",Agra,34,Tajganj,27.157709,78.052421,...,3,Rs.,"['Lunch', 'Serves Alcohol', 'Cash', 'Credit Ca...",4.9,Excellent,470,291,0.0,1,-1

In [4]:
df.drop(columns=["res_id","url"], inplace=True)

In [5]:
df.head()

,name,establishment,address,city,city_id,locality,latitude,longitude,zipcode,country_id,...,price_range,currency,highlights,aggregate_rating,rating_text,votes,photo_count,opentable_support,delivery,takeaway
0,Bikanervala,['Quick Bites'],"Kalyani Point, Near Tulsi Cinema, Bypass Road,...",Agra,34,Khandari,27.211450,78.002381,NaN,1,...,2,Rs.,"['Lunch', 'Takeaway Available', 'Credit Card',...",4.4,Very Good,814,154,0.0,-1,-1
1,Mama Chicken Mama Franky House,['Quick Bites'],"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra,34,Agra Cantt,27.160569,78.011583,282001.0,1,...,2,Rs.,"['Delivery', 'No Alcohol Available', 'Dinner',...",4.4,Very Good,1203,161,0.0,-1,-1
2,Bhagat Halwai,['Quick Bites'],"62/1, Near Easy Day, West Shivaji Nagar, Goalp...",Agra,34,Shahganj,27.182938,77.979684,282010.0,1,...,1,Rs.,"['No Alcohol Available', 'Dinner', 'Takeaway A...",4.2,Very Good,801,107,0.0,1,-1
3,Bhagat Halwai,['Quick Bites'],"Near Anjana Cinema, Nehru Nagar, Civil Lines, ...",Agra,34,Civil Lines,27.205668,78.004799,282002.0,1,...,1,Rs.,"['Takeaway Available', 'Credit Card', 'Lunch',...",4.3,Very Good,693,157,0.0,1,-1
4,The Salt Cafe Kitchen & Bar,['Casual Dining'],"1C,3rd Floor, Fatehabad Road, Tajganj, Agra",Agra,34,Tajganj,27.157709,78.052421,NaN,1,...,3,Rs.,"['Lunch', 'Serves Alcohol', 'Cash', 'Credit Ca...",4.9,Excellent,470,291,0.0,1,-1

In [6]:
# groupby city to rattings
df.isnull().sum()

name                         0
establishment                0
address                    134
city                         0
city_id                      0
locality                     0
latitude                     0
longitude                    0
zipcode                 163187
country_id                   0
locality_verbose             0
cuisines                  1391
timings                   3874
average_cost_for_two         0
price_range                  0
currency                     0
highlights                   0
aggregate_rating             0
rating_text                  0
votes                        0
photo_count                  0
opentable_support           48
delivery                     0
takeaway                     0
dtype: int64

In [7]:
df.groupby("city")

In [12]:
df.groupby(["city"])["rating_text"].count()

city
Agra          2622
Ahmedabad     3162
Ajmer         3277
Alappuzha     1934
Allahabad     2115
              ...
Varanasi      2414
Vellore       2170
Vijayawada    2158
Vizag         2347
Zirakpur       257
Name: rating_text, Length: 99, dtype: int64

In [13]:
df.head(20)

,name,establishment,address,city,city_id,locality,latitude,longitude,zipcode,country_id,...,price_range,currency,highlights,aggregate_rating,rating_text,votes,photo_count,opentable_support,delivery,takeaway
0,Bikanervala,['Quick Bites'],"Kalyani Point, Near Tulsi Cinema, Bypass Road,...",Agra,34,Khandari,27.211450,78.002381,NaN,1,...,2,Rs.,"['Lunch', 'Takeaway Available', 'Credit Card',...",4.4,Very Good,814,154,0.0,-1,-1
1,Mama Chicken Mama Franky House,['Quick Bites'],"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra,34,Agra Cantt,27.160569,78.011583,282001.0,1,...,2,Rs.,"['Delivery', 'No Alcohol Available', 'Dinner',...",4.4,Very Good,1203,161,0.0,-1,-1
2,Bhagat Halwai,['Quick Bites'],"62/1, Near Easy Day, West Shivaji Nagar, Goalp...",Agra,34,Shahganj,27.182938,77.979684,282010.0,1,...,1,Rs.,"['No Alcohol Available', 'Dinner', 'Takeaway A...",4.2,Very Good,801,107,0.0,1,-1
3,Bhagat Halwai,['Quick Bites'],"Near Anjana Cinema, Nehru Nagar, Civil Lines, ...",Agra,34,Civil Lines,27.205668,78.004799,282002.0,1,...,1,Rs.,"['Takeaway Available', 'Credit Card', 'Lunch',...",4.3,Very Good,693,157,0.0,1,-1
4,The Salt Cafe Kitchen & Bar,['Casual Dining'],"1C,3rd Floor, Fatehabad Road, Tajganj, Agra",Agra,34,Tajganj,27.157709,78.052421,NaN,1,...,3,Rs.,"['Lunch', 'Serves Alcohol', 'Cash', 'Credit Ca...",4.9,Excellent,470,291,0.0,1,-1
5,Domino's Pizza,['Quick Bites'],"114/23 G, Deep Shikha Complex, Sanjay Place, C...",Agra,34,Civil Lines,27.201516,78.007556,NaN,1,...,2,Rs.,"['Credit Card', 'Lunch', 'Delivery', 'Dinner',...",4.0,Very Good,707,62,0.0,-1,-1
6,Honeydew Restaurant,['Quick Bites'],"Opposite Soami Bagh Temple, Dayal Bagh, Agra",Agra,34,Dayal Bagh,27.222175,78.010174,282005.0,1,...,2,Rs.,"['Dinner', 'Delivery', 'Lunch', 'Cash', 'Takea...",4.2,Very Good,647,46,0.0,1,-1
7,Domino's Pizza,['Quick Bites'],"Plot C-1/6, Sector 13, Sikandra, Agra",Agra,34,Sikandra,27.203930,77.954260,NaN,1,...,2,Rs.,"['Lunch', 'Delivery', 'Credit Card', 'No Alcoh...",3.8,Good,617,18,0.0,-1,-1
8,Cake House,['Bakery'],"23/301, Wazirpura Rd, Judge Compound Chowraha,...",Agra,34,Civil Lines,27.204148,78.009025,NaN,1,...,2,Rs.,"['Takeaway Available', 'Cash', 'Indoor Seating...",3.4,Average,322,14,0.0,1,-1
9,Sugar N Thyme,['CafÃ©'],"1374 K/1375 K, Ground floor, Dinesh Nagar, Fat...",Agra,34,Tajganj,27.158243,78.045591,282001.0,1,...,3,Rs.,"['No Alcohol Available', 'Dinner', 'Delivery',...",4.4,Very Good,289,324,0.0,1,-1
10,Hichkee,['Casual Dining'],"6/27/1A, Hotel Alleviate, Yamuna Kinara Road, ...",Agra,34,Civil Lines,27.190041,78.024693,282002.0,1,...,3,Rs.,"['Dinner', 'Delivery', 'Credit Card', 'Lunch',...",4.4,Very Good,683,229,0.0,1,-1
11,Bikanervala,['Casual Dining'],"Opposite ITC Mughal, Fatehbad Road, Tajganj, Agra",Agra,34,Tajganj,27.158549,78.045227,282001.0,1,...,2,Rs.,"['Dinner', 'Delivery', 'Breakfast', 'Lunch', '...",4.4,Very Good,523,162,0.0,1,-1
12,Pizza Hut,['Casual Dining'],"8, Handicraft Nagar, Fatehabad Road, Tajganj, ...",Agra,34,Tajganj,27.161372,78.034900,NaN,1,...,2,Rs.,"['Serves Alcohol', 'Cash', 'Takeaway Available...",4.1,Very Good,626,99,0.0,-1,-1
13,Yadav Dhaba Purana,['Dhaba'],"1/48, Delhi Gate, Station Road, Raja Mandi, Ci...",Agra,34,Civil Lines,27.195836,77.998213,NaN,1,...,1,Rs.,"['Lunch', 'Cash', 'No Alcohol Available', 'Din...",4.1,Very Good,361,9,0.0,1,-1
14,Aahar,['Casual Dining'],"26/118, Opposite Income Tax Building, Sanjay P...",Agra,34,Civil Lines,27.199606,78.004528,NaN,1,...,2,Rs.,"['Dinner', 'Delivery', 'Lunch', 'Takeaway Avai...",4.1,Very Good,474,52,0.0,1,-1
15,Domino's Pizza,['Quick Bites'],"Ground & First Floor, City Mall, Balkeshwar Co...",Agra,34,Kamla Nagar,27.212943,78.026549,NaN,1,...,2,Rs.,"['Credit Card', 'Dinner', 'Debit Card', 'Takea...",3.5,Good,490,17,0.0,-1,-1
16,Pinch Of Spice,['Casual Dining'],"23/453, Opposite Sanjay Cinema, Wazipura Road,...",Agra,34,Civil Lines,27.201735,78.007625,NaN,1,...,4,Rs.,"['Lunch', 'Delivery', 'Credit Card', 'Dinner',...",4.6,Excellent,915,105,0.0,1,-1
17,Mc Donald's,['Quick Bites'],"4-5, Ashok Cosmos Mall, Sanjay Place, Civil Li...",Agra,34,Civil Lines,27.201366,78.008746,NaN,1,...,2,Rs.,"['Lunch', 'Credit Card', 'No Alcohol Available...",4.3,Very Good,837,45,0.0,-1,-1
18,GMB - Gopika Sweets & Restaurant,['Casual Dining'],"Crystal Tower, Fatehabad Road, Tajganj, Agra",Agra,34,Tajganj,27.162010,78.037996,NaN,1,...,2,Rs.,"['Dinner', 'Takeaway Available', 'Breakfast', ...",4.1,Very Good,362,86,0.0,-1,-1
19,The Greener Side,['Quick Bites'],Delhi Gate Rd,Agra,34,Civil Lines,27.197103,77.998170,282002.0,1,...,1,Rs.,"['Cash', 'Delivery', 'No Alcohol Available', '...",4.4,Very Good,490,77,0.0,1,-1

In [26]:
count = df.groupby('city')['aggregate_rating'].mean()
count

city
Agra          3.493860
Ahmedabad     3.813978
Ajmer         3.554623
Alappuzha     0.858842
Allahabad     3.485248
                ...
Varanasi      3.667730
Vellore       2.987788
Vijayawada    3.618026
Vizag         3.640094
Zirakpur      3.236576
Name: aggregate_rating, Length: 99, dtype: float64

In [ ]:
count = df.groupby('city').apply(lambda x: len(x)).reset_index
count